credentials:
  usernames:
    testuser:
      name: Test Benutzer
      password: '$2b$12$WaNuvcuwGUS8bTDDTZ9Et.ha3s0AYJjRMUUbCxsHDpyqkrmlDw7DC'  # test123

cookie:
  name: zaehlercookie
  key: geheimkey
  expiry_days: 30
